#!/bin/bash

# 说明脚本：演示如何在没有完整ROS环境的情况下构建项目
echo "当前环境缺少ROS，无法直接使用catkin build或catkin_make构建项目"
echo "要构建jaka_close_contro包，需要先安装ROS环境"
echo ""
echo "推荐的安装步骤："
echo "1. 添加ROS软件源"
echo "   sudo sh -c 'echo \"deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main\" > /etc/apt/sources.list.d/ros-latest.list'"
echo "2. 安装密钥"
echo "   sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
echo "3. 更新包列表"
echo "   sudo apt update"
echo "4. 安装ROS Noetic"
echo "   sudo apt install ros-noetic-desktop-full"
echo "5. 初始化rosdep"
echo "   sudo rosdep init"
echo "   rosdep update"
echo "6. 设置环境"
echo "   echo \"source /opt/ros/noetic/setup.bash\" >> ~/.bashrc"
echo "   source ~/.bashrc"
echo "7. 安装依赖"
echo "   sudo apt install python3-rosdep python3-catkin-tools python3-rospkg"
echo "8. 在catkin工作空间中构建"
echo "   cd ~/catkin_ws"
echo "   catkin build jaka_close_contro"
echo ""
echo "注意：包的正确名称是 'jaka_close_contro'（不是jaka_close_control）"